/*
 * ============================================================================
 * Exact Time Integration for Interstellar Gas Cooling/Heating
 * Header File
 * ============================================================================
 * 
 * Implementation based on:
 *   Zhu, Smith & Hernquist (2017), MNRAS 470, 1017-1025
 *   "Gas cooling in hydrodynamic simulations with an exact time integration scheme"
 *
 * Usage:
 *   1. Call load_cooling_table("cooling_rate_grid.bin") to load the table
 *   2. Call exact_integrate(nH, Z, T_init, dt, &T_final) to integrate
 *   3. Call free_cooling_table() when done
 *
 * ============================================================================
 */

#ifndef EXACT_COOLING_INTEGRATOR_H
#define EXACT_COOLING_INTEGRATOR_H

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Physical Constants (CGS units)
 * ============================================================================ */
#define ECI_K_BOLTZMANN     1.3806504e-16   /* Boltzmann constant [erg/K] */
#define ECI_M_PROTON        1.6726219e-24   /* Proton mass [g] */
#define ECI_GAMMA           (5.0/3.0)       /* Adiabatic index */
#define ECI_YEAR_IN_SEC     3.15576e7       /* Seconds per year */
#define ECI_MYR_IN_SEC      3.15576e13      /* Seconds per Myr */

/* ============================================================================
 * Data Loading Functions
 * ============================================================================ */

/**
 * Load cooling/heating rate table from binary file
 * 
 * The binary file should be generated by cooling_rate_mpi.c and contains:
 *   - GridParams structure (dimensions and ranges)
 *   - cooling_rate array [L * M * N] doubles
 *   - heating_rate array [L * M * N] doubles
 * 
 * @param filename  Path to the binary file
 * @return          0 on success, -1 on failure
 */
int load_cooling_table(const char *filename);

/**
 * Free all memory allocated for the cooling table
 */
void free_cooling_table(void);

/**
 * Print information about the loaded cooling table
 */
void print_table_info(void);

/* ============================================================================
 * Integration Functions
 * ============================================================================ */

/**
 * Exact time integration of cooling/heating
 * 
 * Uses the method from Zhu et al. (2017), MNRAS 470, 1017:
 *   - Eq. (4): Y(u) temporal evolution function
 *   - Eq. (5): Linear interpolation of Lambda(u)
 *   - Eq. (6-8): Segment integration formulas
 *   - Eq. (9): Cumulative Y construction
 *   - Eq. (10): Delta_Y calculation for timestep
 * 
 * @param nH        Hydrogen number density [cm^-3]
 * @param Z         Metallicity [Z_solar]
 * @param T_init    Initial temperature [K]
 * @param dt        Timestep [seconds]
 * @param T_final   Pointer to store final temperature [K]
 * @return          Temperature change dT = T_final - T_init [K]
 */
double exact_integrate(double nH, double Z, double T_init, double dt, double *T_final);

/**
 * Simple Euler integration (for comparison/debugging)
 * 
 * Uses first-order forward Euler: u_new = u_old - Lambda * dt
 * 
 * @param nH        Hydrogen number density [cm^-3]
 * @param Z         Metallicity [Z_solar]
 * @param T_init    Initial temperature [K]
 * @param dt        Timestep [seconds]
 * @param T_final   Pointer to store final temperature [K]
 * @return          Temperature change dT = T_final - T_init [K]
 */
double euler_integrate(double nH, double Z, double T_init, double dt, double *T_final);

/* ============================================================================
 * Utility Functions
 * ============================================================================ */

/**
 * Get cooling time t_cool = u / |Lambda|
 * 
 * @param nH    Hydrogen number density [cm^-3]
 * @param Z     Metallicity [Z_solar]
 * @param T     Temperature [K]
 * @return      Cooling time [seconds]
 */
double get_cooling_time(double nH, double Z, double T);

/**
 * Get net cooling rate Lambda(nH, Z, T)
 * 
 * Positive value indicates cooling (energy loss)
 * Negative value indicates heating (energy gain)
 * 
 * @param nH    Hydrogen number density [cm^-3]
 * @param Z     Metallicity [Z_solar]
 * @param T     Temperature [K]
 * @return      Net cooling rate [erg/g/s]
 */
double get_net_cooling_rate(double nH, double Z, double T);

/* ============================================================================
 * Fast Interpolation Functions (Lookup Table)
 * ============================================================================ */

/**
 * Build dT lookup table for fast interpolation
 * 
 * Pre-computes dT = T_new - T_init for each grid point using exact_integrate().
 * This allows O(1) trilinear interpolation instead of the full exact
 * integration algorithm, providing significant speedup.
 * 
 * @param dt    The fixed timestep [seconds] for which to build the table
 * @return      0 on success, -1 on failure
 */
int build_dT_lookup_table(double dt);

/**
 * Free dT lookup table memory
 * 
 * Releases memory used by the dT lookup table without freeing the entire
 * cooling table.
 */
void free_dT_lookup_table(void);

/**
 * Fast exact integration via lookup table interpolation
 * 
 * Performs the same calculation as exact_integrate() but uses
 * a pre-computed lookup table with trilinear interpolation for speed.
 * 
 * The dT lookup table must be built first with build_dT_lookup_table(dt).
 * This function uses the same timestep dt that was used to build the table.
 * 
 * @param nH        Hydrogen number density [cm^-3]
 * @param Z         Metallicity [Z_solar]
 * @param T_init    Initial temperature [K]
 * @param T_final   Pointer to store final temperature [K]
 * @return          Temperature change dT = T_final - T_init [K]
 */
double interpolate_exact_integrate(double nH, double Z, double T_init, double *T_final);

/**
 * Get the timestep used for the current dT lookup table
 * 
 * @return  The timestep [seconds] used to build the dT lookup table,
 *          or 0.0 if the table is not built.
 */
double get_dT_table_timestep(void);

/**
 * Check if dT lookup table is available
 * 
 * @return  1 if the dT lookup table is built and ready, 0 otherwise.
 */
int is_dT_table_loaded(void);

#ifdef __cplusplus
}
#endif

#endif /* EXACT_COOLING_INTEGRATOR_H */
