/*
 * ============================================================================
 * Exact Time Integration for Interstellar Gas Cooling/Heating
 * ============================================================================
 * 
 * Implementation based on:
 *   Zhu, Smith & Hernquist (2017), MNRAS 470, 1017-1025
 *   "Gas cooling in hydrodynamic simulations with an exact time integration scheme"
 *   https://doi.org/10.1093/mnras/stx1346
 *
 * Original method from:
 *   Townsend (2009), ApJS 181, 391
 *
 * Key Equations from the paper:
 *   Eq. (3):  u = kT / ((gamma-1) * mu * m_H)           [specific internal energy]
 *   Eq. (4):  Y(u) = (Lambda_ref/u_ref) * integral du/Lambda(u)  [temporal function]
 *   Eq. (5):  Lambda(u) = ((L2-L1)/(u2-u1))*(u-u1) + L1  [linear interpolation]
 *   Eq. (6):  dY = (Lambda_ref/u_ref) * A * ln((B+u2)/(B+u1))  if L2 != L1
 *   Eq. (7):  dY = (Lambda_ref/u_ref) * (u2-u1)/L1             if L2 == L1
 *   Eq. (8):  A = (u2-u1)/(L2-L1), B = (u2*L1-u1*L2)/(L2-L1)
 *   Eq. (9):  Y(u) = sum of dY                          [cumulative sum]
 *   Eq. (10): DeltaY = (u_i/Lambda_i) * (Lambda_ref/u_ref) * (dt/t_cool)
 *
 * This code reads cooling/heating rate tables from binary file generated by
 * cooling_rate_mpi.c (using CLOUDY) and integrates the cooling equation exactly.
 *
 * ============================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <time.h>
#include <omp.h>

/* Define M_PI if not available */
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

/* Include the mean molecular weight calculator header */
#include "getMU.h"

/* ============================================================================
 * Physical Constants (CGS units)
 * ============================================================================ */
#define K_BOLTZMANN     1.3806504e-16   /* Boltzmann constant [erg/K] */
#define M_PROTON        1.6726219e-24   /* Proton mass [g] */
#define M_HELIUM        (4.002602 * M_PROTON)  /* Helium atom mass [g] */
#define GAMMA           (5.0/3.0)       /* Adiabatic index for monatomic ideal gas */
#define YEAR_IN_SEC     3.15576e7       /* Seconds per year */
#define MYR_IN_SEC      3.15576e13      /* Seconds per Myr */

/* ============================================================================
 * Primordial Abundances (Big Bang Nucleosynthesis values)
 * ============================================================================ */
#define X_PRIMORDIAL    0.76            /* Primordial hydrogen mass fraction */
#define Y_PRIMORDIAL    0.24            /* Primordial helium mass fraction */
#define Z_SOLAR         0.0134          /* Solar metallicity (Asplund et al. 2009) */

/* ============================================================================
 * Configuration - must match cooling_rate_mpi.c
 * ============================================================================ */
#include "cooling_rate_mpi.h"

/* Tolerance for floating point comparisons */
#define EPSILON         1.0e-30
#define REL_TOLERANCE   1.0e-8

/* ============================================================================
 * Mass Fraction Structure
 * ============================================================================ */
typedef struct {
    double X;       /* Hydrogen mass fraction */
    double Y;       /* Helium mass fraction */
    double Z;       /* Metal mass fraction */
} MassFractions;

/* ============================================================================
 * Calculate mass fractions from metallicity
 * 
 * Given metallicity Z_metal in solar units:
 *   Z = Z_metal * Z_solar
 *   X = X_primordial * (1 - Z) / (X_primordial + Y_primordial)
 *   Y = Y_primordial * (1 - Z) / (X_primordial + Y_primordial)
 * 
 * This ensures X + Y + Z = 1
 * ============================================================================ */
static MassFractions calc_mass_fractions(double Z_metal) {
    MassFractions mf;
    
    /* Metal mass fraction */
    mf.Z = Z_metal * Z_SOLAR;
    if (mf.Z < 0.0) mf.Z = 0.0;
    if (mf.Z > 1.0) mf.Z = 1.0;
    
    /* Scale primordial abundances to maintain X + Y + Z = 1 */
    double f = (1.0 - mf.Z) / (X_PRIMORDIAL + Y_PRIMORDIAL);
    mf.X = X_PRIMORDIAL * f;
    mf.Y = Y_PRIMORDIAL * f;
    
    return mf;
}

/* ============================================================================
 * Convert hydrogen number density to gas mass density
 * 
 * n_H = rho * X / m_H
 * Therefore: rho = n_H * m_H / X
 * 
 * where X is the hydrogen mass fraction
 * ============================================================================ */
static double nH_to_rho(double nH, double Z_metal) {
    MassFractions mf = calc_mass_fractions(Z_metal);
    return nH * M_PROTON / mf.X;
}

/* ============================================================================
 * Convert gas mass density to hydrogen number density
 * 
 * n_H = rho * X / m_H
 * ============================================================================ */
static double rho_to_nH(double rho, double Z_metal) {
    MassFractions mf = calc_mass_fractions(Z_metal);
    return rho * mf.X / M_PROTON;
}

/* ============================================================================
 * Calculate mean molecular weight
 * 
 * For fully ionized gas:
 *   mu = 1 / (2X + 3Y/4 + Z/2)
 *   (assuming metals have average A/Z ~ 2)
 * 
 * For fully neutral gas:
 *   mu = 1 / (X + Y/4 + Z/A_metal)
 *   where A_metal ~ 16 for typical ISM metals (O, C, N, etc.)
 * 
 * This function provides smooth interpolation between these limits
 * based on temperature.
 * ============================================================================ */
static double calc_mean_molecular_weight(double T, double Z_metal) {
    MassFractions mf = calc_mass_fractions(Z_metal);
    
    /* Ionization transition temperatures */
    const double T_ionize_low = 6000.0;    /* Start of H ionization */
    const double T_ionize_high = 20000.0;  /* Fully ionized */
    
    /* Mean atomic weight of metals (dominated by O, C, N) */
    const double A_metal = 16.0;
    
    /* Fully neutral mean molecular weight */
    /* mu_neutral = 1 / (X + Y/4 + Z/A_metal) */
    double denom_neutral = mf.X + mf.Y / 4.0 + mf.Z / A_metal;
    double mu_neutral = 1.0 / denom_neutral;
    
    /* Fully ionized mean molecular weight */
    /* mu_ionized = 1 / (2X + 3Y/4 + Z/2) */
    /* For metals: assume average A/Z ~ 2 (like O with A=16, Z=8) */
    double denom_ionized = 2.0 * mf.X + 0.75 * mf.Y + mf.Z / 2.0;
    double mu_ionized = 1.0 / denom_ionized;
    
    /* Smooth interpolation based on temperature */
    if (T <= T_ionize_low) {
        return mu_neutral;
    } else if (T >= T_ionize_high) {
        return mu_ionized;
    } else {
        /* Smooth transition using cosine interpolation */
        double f = (T - T_ionize_low) / (T_ionize_high - T_ionize_low);
        f = 0.5 * (1.0 - cos(M_PI * f));  /* Smooth S-curve */
        return mu_neutral * (1.0 - f) + mu_ionized * f;
    }
}

/* ============================================================================
 * Data Structures - matching cooling_rate_mpi.c
 * ============================================================================ */

/* Grid parameters structure - must match cooling_rate_mpi.c exactly */
/* Cooling table structure */
typedef struct {
    GridParams params;                  /* Grid parameters */
    
    double *density;                    /* Density grid [cm^-3], size L */
    double *metallicity;                /* Metallicity grid [Z_solar], size M */
    double *temperature;                /* Temperature grid [K], size N */
    
    double *cooling_rate;               /* Cooling rate Lambda [erg/g/s], size L*M*N */
    double *heating_rate;               /* Heating rate Gamma [erg/g/s], size L*M*N */
    double *net_rate;                   /* Net rate = cooling - heating [erg/g/s] */
    
    /* Pre-computed Y function for exact integration */
    double *Y_table;                    /* Y(T) at each temperature point, size L*M*N */
    
    /* Pre-computed lookup table for fast interpolation */
    double *log_T_final_table;          /* log10(T_final) at each grid point, size L*M*N */
    double dT_table_dt;                 /* Timestep used to build the table [s] */
    int dT_table_loaded;                /* Flag indicating if lookup table is built */
    
    int loaded;                         /* Flag indicating if table is loaded */
} CoolingTable;

/* Global cooling table */
static CoolingTable g_table = {0};

/* ============================================================================
 * Helper Functions
 * ============================================================================ */

/* Clamp value between min and max */
static double clamp(double x, double a, double b) {
    return (x < a) ? a : ((x > b) ? b : x);
}

/* Safe log10 that handles zero/negative values */
static double safe_log10(double x) {
    return (x > 0) ? log10(x) : -30.0;
}

/* Linear interpolation */
static double lerp(double x0, double x1, double f) {
    return x0 + f * (x1 - x0);
}

/* Find index in sorted array (log-spaced) */
static int find_index_log(const double *arr, int n, double val) {
    if (val <= arr[0]) return 0;
    if (val >= arr[n-1]) return n - 2;
    
    double log_val = safe_log10(val);
    double log_min = safe_log10(arr[0]);
    double log_max = safe_log10(arr[n-1]);
    double step = (log_max - log_min) / (n - 1);
    
    int idx = (int)((log_val - log_min) / step);
    idx = (idx < 0) ? 0 : ((idx >= n - 1) ? n - 2 : idx);
    
    /* Fine-tune the index */
    while (idx > 0 && arr[idx] > val) idx--;
    while (idx < n - 2 && arr[idx + 1] < val) idx++;
    
    return idx;
}

/* Find index in array (possibly non-uniform spacing) */
static int find_index(const double *arr, int n, double val) {
    if (val <= arr[0]) return 0;
    if (val >= arr[n-1]) return n - 2;
    
    /* Binary search */
    int lo = 0, hi = n - 1;
    while (hi - lo > 1) {
        int mid = (lo + hi) / 2;
        if (arr[mid] > val)
            hi = mid;
        else
            lo = mid;
    }
    return lo;
}

/* ============================================================================
 * Eq. (3): Thermodynamic Conversions
 *          u = kT / ((gamma-1) * mu * m_H)
 * ============================================================================ */

/* Convert temperature to specific internal energy */
/* Eq. (3): T -> u */
static double T_to_u(double T, double mu) {
    return K_BOLTZMANN * T / ((GAMMA - 1.0) * mu * M_PROTON);
}

/* Convert specific internal energy to temperature */
/* Inverse of Eq. (3): u -> T */
static double u_to_T(double u, double mu) {
    return u * (GAMMA - 1.0) * mu * M_PROTON / K_BOLTZMANN;
}

/* ============================================================================
 * Table Index Calculation
 * ============================================================================ */

/* Get flat array index from (i_dens, j_metal, k_temp) */
static inline int get_index(int i, int j, int k, int L, int M, int N) {
    /* Storage order: [density][metallicity][temperature] */
    /* From cooling_rate_mpi.c: id = i * M + j, then cooling_grid[id * N + k] */
    return (i * M + j) * N + k;
}

/* ============================================================================
 * Trilinear Interpolation
 * ============================================================================ */

/* Interpolate net cooling rate Lambda(n_H, Z, T) */
/* Positive = cooling (energy loss), Negative = heating (energy gain) */
static double interp_net_rate(double nH, double Z, double T) {
    CoolingTable *ct = &g_table;
    
    if (!ct->loaded) {
        fprintf(stderr, "Error: Cooling table not loaded!\n");
        return 0.0;
    }
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    
    /* Find indices and fractions for density */
    int i = find_index_log(ct->density, L, nH);
    double f_n;
    if (ct->density[i+1] > ct->density[i]) {
        f_n = (safe_log10(nH) - safe_log10(ct->density[i])) / 
              (safe_log10(ct->density[i+1]) - safe_log10(ct->density[i]));
    } else {
        f_n = 0.0;
    }
    f_n = clamp(f_n, 0.0, 1.0);
    
    /* Find indices and fractions for metallicity */
    int j = find_index_log(ct->metallicity, M, Z);
    double f_z;
    if (ct->metallicity[j+1] > ct->metallicity[j]) {
        f_z = (safe_log10(Z) - safe_log10(ct->metallicity[j])) / 
              (safe_log10(ct->metallicity[j+1]) - safe_log10(ct->metallicity[j]));
    } else {
        f_z = 0.0;
    }
    f_z = clamp(f_z, 0.0, 1.0);
    
    /* Find indices and fractions for temperature */
    int k = find_index(ct->temperature, N, T);
    double f_t;
    if (ct->temperature[k+1] > ct->temperature[k]) {
        f_t = (safe_log10(T) - safe_log10(ct->temperature[k])) / 
              (safe_log10(ct->temperature[k+1]) - safe_log10(ct->temperature[k]));
    } else {
        f_t = 0.0;
    }
    f_t = clamp(f_t, 0.0, 1.0);
    
    /* Trilinear interpolation */
    double c000 = ct->net_rate[get_index(i,   j,   k,   L, M, N)];
    double c001 = ct->net_rate[get_index(i,   j,   k+1, L, M, N)];
    double c010 = ct->net_rate[get_index(i,   j+1, k,   L, M, N)];
    double c011 = ct->net_rate[get_index(i,   j+1, k+1, L, M, N)];
    double c100 = ct->net_rate[get_index(i+1, j,   k,   L, M, N)];
    double c101 = ct->net_rate[get_index(i+1, j,   k+1, L, M, N)];
    double c110 = ct->net_rate[get_index(i+1, j+1, k,   L, M, N)];
    double c111 = ct->net_rate[get_index(i+1, j+1, k+1, L, M, N)];
    
    double c00 = lerp(c000, c001, f_t);
    double c01 = lerp(c010, c011, f_t);
    double c10 = lerp(c100, c101, f_t);
    double c11 = lerp(c110, c111, f_t);
    
    double c0 = lerp(c00, c01, f_z);
    double c1 = lerp(c10, c11, f_z);
    
    return lerp(c0, c1, f_n);
}

/* Interpolate cooling rate only */
static double interp_cooling_rate(double nH, double Z, double T) {
    CoolingTable *ct = &g_table;
    
    if (!ct->loaded) return 0.0;
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    
    int i = find_index_log(ct->density, L, nH);
    int j = find_index_log(ct->metallicity, M, Z);
    int k = find_index(ct->temperature, N, T);
    
    double f_n = (safe_log10(nH) - safe_log10(ct->density[i])) / 
                 (safe_log10(ct->density[i+1]) - safe_log10(ct->density[i]) + 1e-30);
    double f_z = (safe_log10(Z) - safe_log10(ct->metallicity[j])) / 
                 (safe_log10(ct->metallicity[j+1]) - safe_log10(ct->metallicity[j]) + 1e-30);
    double f_t = (safe_log10(T) - safe_log10(ct->temperature[k])) / 
                 (safe_log10(ct->temperature[k+1]) - safe_log10(ct->temperature[k]) + 1e-30);
    
    f_n = clamp(f_n, 0.0, 1.0);
    f_z = clamp(f_z, 0.0, 1.0);
    f_t = clamp(f_t, 0.0, 1.0);
    
    double c000 = ct->cooling_rate[get_index(i,   j,   k,   L, M, N)];
    double c001 = ct->cooling_rate[get_index(i,   j,   k+1, L, M, N)];
    double c010 = ct->cooling_rate[get_index(i,   j+1, k,   L, M, N)];
    double c011 = ct->cooling_rate[get_index(i,   j+1, k+1, L, M, N)];
    double c100 = ct->cooling_rate[get_index(i+1, j,   k,   L, M, N)];
    double c101 = ct->cooling_rate[get_index(i+1, j,   k+1, L, M, N)];
    double c110 = ct->cooling_rate[get_index(i+1, j+1, k,   L, M, N)];
    double c111 = ct->cooling_rate[get_index(i+1, j+1, k+1, L, M, N)];
    
    double c00 = lerp(c000, c001, f_t);
    double c01 = lerp(c010, c011, f_t);
    double c10 = lerp(c100, c101, f_t);
    double c11 = lerp(c110, c111, f_t);
    
    double c0 = lerp(c00, c01, f_z);
    double c1 = lerp(c10, c11, f_z);
    
    return lerp(c0, c1, f_n);
}

/* Interpolate heating rate only */
static double interp_heating_rate(double nH, double Z, double T) {
    CoolingTable *ct = &g_table;
    
    if (!ct->loaded) return 0.0;
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    
    int i = find_index_log(ct->density, L, nH);
    int j = find_index_log(ct->metallicity, M, Z);
    int k = find_index(ct->temperature, N, T);
    
    double f_n = (safe_log10(nH) - safe_log10(ct->density[i])) / 
                 (safe_log10(ct->density[i+1]) - safe_log10(ct->density[i]) + 1e-30);
    double f_z = (safe_log10(Z) - safe_log10(ct->metallicity[j])) / 
                 (safe_log10(ct->metallicity[j+1]) - safe_log10(ct->metallicity[j]) + 1e-30);
    double f_t = (safe_log10(T) - safe_log10(ct->temperature[k])) / 
                 (safe_log10(ct->temperature[k+1]) - safe_log10(ct->temperature[k]) + 1e-30);
    
    f_n = clamp(f_n, 0.0, 1.0);
    f_z = clamp(f_z, 0.0, 1.0);
    f_t = clamp(f_t, 0.0, 1.0);
    
    double c000 = ct->heating_rate[get_index(i,   j,   k,   L, M, N)];
    double c001 = ct->heating_rate[get_index(i,   j,   k+1, L, M, N)];
    double c010 = ct->heating_rate[get_index(i,   j+1, k,   L, M, N)];
    double c011 = ct->heating_rate[get_index(i,   j+1, k+1, L, M, N)];
    double c100 = ct->heating_rate[get_index(i+1, j,   k,   L, M, N)];
    double c101 = ct->heating_rate[get_index(i+1, j,   k+1, L, M, N)];
    double c110 = ct->heating_rate[get_index(i+1, j+1, k,   L, M, N)];
    double c111 = ct->heating_rate[get_index(i+1, j+1, k+1, L, M, N)];
    
    double c00 = lerp(c000, c001, f_t);
    double c01 = lerp(c010, c011, f_t);
    double c10 = lerp(c100, c101, f_t);
    double c11 = lerp(c110, c111, f_t);
    
    double c0 = lerp(c00, c01, f_z);
    double c1 = lerp(c10, c11, f_z);
    
    return lerp(c0, c1, f_n);
}

/* ============================================================================
 * Eq. (6), (7), (8): Calculate deltaY for a segment
 *
 * For linear interpolation of Lambda(u) between (u1, L1) and (u2, L2):
 *   Eq. (5):  Lambda(u) = ((L2-L1)/(u2-u1))*(u-u1) + L1
 *
 * The integral delta_Y = (Lambda_ref/u_ref) * integral_{u1}^{u2} du/Lambda(u)
 *
 * If L1 != L2 (Eq. 6, 8):
 *   A = (u2-u1)/(L2-L1)
 *   B = (u2*L1 - u1*L2)/(L2-L1)
 *   delta_Y = (Lambda_ref/u_ref) * A * ln((B+u2)/(B+u1))
 *
 * If L1 == L2 (Eq. 7):
 *   delta_Y = (Lambda_ref/u_ref) * (u2-u1)/L1
 *
 * ============================================================================ */
static double calc_delta_Y(double u1, double u2, double L1, double L2,
                           double u_ref, double L_ref) {
    /* Eq. (6), (7), (8) */
    
    double du = u2 - u1;
    double dL = L2 - L1;
    
    /* Reference normalization factor: (Lambda_ref / u_ref) */
    double norm = L_ref / u_ref;
    
    /* Check if Lambda values are essentially equal */
    /* Eq. (7): delta_Y = (Lambda_ref/u_ref) * (u2-u1)/L1 */
    if (fabs(dL) < REL_TOLERANCE * fabs(L1 + L2) * 0.5 + EPSILON) {
        double L_avg = 0.5 * (L1 + L2);
        if (fabs(L_avg) < EPSILON) {
            /* Zero cooling rate - no change in Y */
            return 0.0;
        }
        return norm * du / L_avg;
    }
    
    /* Eq. (8): A = (u2-u1)/(L2-L1), B = (u2*L1 - u1*L2)/(L2-L1) */
    double A = du / dL;
    double B = (u2 * L1 - u1 * L2) / dL;
    
    /* Check for valid logarithm arguments */
    /* The argument (B + u) should be positive */
    double arg1 = B + u1;
    double arg2 = B + u2;
    
    if (arg1 * arg2 <= 0 || fabs(arg1) < EPSILON || fabs(arg2) < EPSILON) {
        /* Fallback to simple average */
        double L_avg = 0.5 * (L1 + L2);
        if (fabs(L_avg) < EPSILON) return 0.0;
        return norm * du / L_avg;
    }
    
    /* Eq. (6): delta_Y = (Lambda_ref/u_ref) * A * ln((B+u2)/(B+u1)) */
    double delta_Y = norm * A * log(arg2 / arg1);
    
    return delta_Y;
}

/* ============================================================================
 * Build Y function table for given (n_H, Z)
 *
 * Eq. (9): Y(u) = sum of delta_Y from u_ref to u
 *
 * We construct Y(T_k) for each temperature grid point.
 * Y increases monotonically for cooling (Lambda > 0).
 * Y decreases monotonically for heating (Lambda < 0).
 *
 * ============================================================================ */
static void build_Y_table_for_cell(int i, int j) {
    CoolingTable *ct = &g_table;
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    
    double nH = ct->density[i];
    double Z_metal = ct->metallicity[j];
    
    /* Calculate gas mass density from nH using proper mass fractions */
    double rho = nH_to_rho(nH, Z_metal);
    (void)rho;  /* May be used by get_mean_molecular_weight when USE_GETMU is defined */
    
    /* Choose reference point at middle temperature */
    int k_ref = N / 2;
    double T_ref = ct->temperature[k_ref];
    double L_ref = ct->net_rate[get_index(i, j, k_ref, L, M, N)];
    
    /* Avoid zero reference */
    if (fabs(L_ref) < EPSILON) {
        /* Find non-zero reference */
        for (int k = 0; k < N; k++) {
            double L_k = ct->net_rate[get_index(i, j, k, L, M, N)];
            if (fabs(L_k) > EPSILON) {
                k_ref = k;
                T_ref = ct->temperature[k_ref];
                L_ref = L_k;
                break;
            }
        }
    }
    if (fabs(L_ref) < EPSILON) L_ref = 1.0e-30;
    
    /* Get mu at reference point */
    double mu_ref;
#ifdef USE_GETMU
    mu_ref = get_mean_molecular_weight(rho, T_ref, Z_metal);
#else
//    mu_ref = calc_mean_molecular_weight(T_ref, Z_metal);
    mu_ref = calculate_mu(rho, T_ref, Z_metal);
#endif
    
    double u_ref = T_to_u(T_ref, mu_ref);
    
    /* Set Y = 0 at reference point */
    ct->Y_table[get_index(i, j, k_ref, L, M, N)] = 0.0;
    
    /* Eq. (9): Build Y by summing delta_Y from reference to higher T */
    double Y_accum = 0.0;
    for (int k = k_ref + 1; k < N; k++) {
        double T1 = ct->temperature[k - 1];
        double T2 = ct->temperature[k];
        double L1 = ct->net_rate[get_index(i, j, k - 1, L, M, N)];
        double L2 = ct->net_rate[get_index(i, j, k, L, M, N)];
        
        /* Get mu values */
        double mu1, mu2;
#ifdef USE_GETMU
        mu1 = get_mean_molecular_weight(rho, T1, Z_metal);
        mu2 = get_mean_molecular_weight(rho, T2, Z_metal);
#else
//        mu1 = calc_mean_molecular_weight(T1, Z_metal);
//       mu2 = calc_mean_molecular_weight(T2, Z_metal);
    	mu1 = calculate_mu(rho, T1, Z_metal);
    	mu2 = calculate_mu(rho, T2, Z_metal);
#endif
        
        double u1 = T_to_u(T1, mu1);
        double u2 = T_to_u(T2, mu2);
        
        /* Skip if either Lambda is near zero or changes sign */
        if (fabs(L1) < EPSILON || fabs(L2) < EPSILON || L1 * L2 < 0) {
            ct->Y_table[get_index(i, j, k, L, M, N)] = Y_accum;
            continue;
        }
        
        double dY = calc_delta_Y(u1, u2, L1, L2, u_ref, L_ref);
        Y_accum += dY;
        ct->Y_table[get_index(i, j, k, L, M, N)] = Y_accum;
    }
    
    /* Eq. (9): Build Y by summing delta_Y from reference to lower T */
    Y_accum = 0.0;
    for (int k = k_ref - 1; k >= 0; k--) {
        double T1 = ct->temperature[k + 1];
        double T2 = ct->temperature[k];
        double L1 = ct->net_rate[get_index(i, j, k + 1, L, M, N)];
        double L2 = ct->net_rate[get_index(i, j, k, L, M, N)];
        
        double mu1, mu2;
#ifdef USE_GETMU
        mu1 = get_mean_molecular_weight(rho, T1, Z_metal);
        mu2 = get_mean_molecular_weight(rho, T2, Z_metal);
#else
//        mu1 = calc_mean_molecular_weight(T1, Z_metal);
//        mu2 = calc_mean_molecular_weight(T2, Z_metal);
        mu1 = calculate_mu(rho,T1, Z_metal);
        mu2 = calculate_mu(rho,T2, Z_metal);
#endif
        
        double u1 = T_to_u(T1, mu1);
        double u2 = T_to_u(T2, mu2);
        
        if (fabs(L1) < EPSILON || fabs(L2) < EPSILON || L1 * L2 < 0) {
            ct->Y_table[get_index(i, j, k, L, M, N)] = Y_accum;
            continue;
        }
        
        double dY = calc_delta_Y(u1, u2, L1, L2, u_ref, L_ref);
        Y_accum += dY;
        ct->Y_table[get_index(i, j, k, L, M, N)] = Y_accum;
    }
}

/* ============================================================================
 * Load Cooling Table from Binary File
 * 
 * Binary file format (from cooling_rate_mpi.c):
 *   1. GridParams structure
 *   2. cooling_grid[L * M * N] doubles
 *   3. heating_grid[L * M * N] doubles
 *
 * ============================================================================ */
int load_cooling_table(const char *filename) {
    CoolingTable *ct = &g_table;
    
    /* Free previous data if any */
    if (ct->loaded) {
        free(ct->density);
        free(ct->metallicity);
        free(ct->temperature);
        free(ct->cooling_rate);
        free(ct->heating_rate);
        free(ct->net_rate);
        free(ct->Y_table);
        ct->loaded = 0;
    }
    
    FILE *fp = fopen(filename, "rb");
    if (!fp) {
        fprintf(stderr, "Error: Cannot open file '%s'\n", filename);
        return -1;
    }
    
    /* Read grid parameters */
    if (fread(&ct->params, sizeof(GridParams), 1, fp) != 1) {
        fprintf(stderr, "Error: Failed to read grid parameters\n");
        fclose(fp);
        return -1;
    }
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    size_t total_size = (size_t)L * M * N;
    
    printf("Loading cooling table: %s\n", filename);
    printf("  Grid dimensions: L=%d (density), M=%d (metallicity), N=%d (temperature)\n", L, M, N);
    printf("  redshift %f\n", ct->params.redshift);
    printf("  Density range: [%.2e, %.2e] cm^-3\n", ct->params.density_min, ct->params.density_max);
    printf("  Metallicity range: [%.2e, %.2e] Z_solar\n", ct->params.metallicity_min, ct->params.metallicity_max);
    printf("  Temperature range: [%.2e, %.2e] K\n", ct->params.temp_min, ct->params.temp_max);
    
    /* Allocate memory */
    ct->density = (double*)malloc(L * sizeof(double));
    ct->metallicity = (double*)malloc(M * sizeof(double));
    ct->temperature = (double*)malloc(N * sizeof(double));
    ct->cooling_rate = (double*)malloc(total_size * sizeof(double));
    ct->heating_rate = (double*)malloc(total_size * sizeof(double));
    ct->net_rate = (double*)malloc(total_size * sizeof(double));
    ct->Y_table = (double*)malloc(total_size * sizeof(double));
    
    if (!ct->density || !ct->metallicity || !ct->temperature ||
        !ct->cooling_rate || !ct->heating_rate || !ct->net_rate || !ct->Y_table) {
        fprintf(stderr, "Error: Memory allocation failed\n");
        fclose(fp);
        return -1;
    }
    
    /* Build density grid (log-spaced) */
    double log_dens_min = log10(ct->params.density_min);
    double log_dens_max = log10(ct->params.density_max);
    double dens_step = (log_dens_max - log_dens_min) / (L - 1);
    for (int i = 0; i < L; i++) {
        ct->density[i] = pow(10.0, log_dens_min + i * dens_step);
    }
    
    /* Build metallicity grid (log-spaced) */
    double log_metal_min = log10(ct->params.metallicity_min);
    double log_metal_max = log10(ct->params.metallicity_max);
    double metal_step = (log_metal_max - log_metal_min) / (M - 1);
    for (int j = 0; j < M; j++) {
        ct->metallicity[j] = pow(10.0, log_metal_min + j * metal_step);
    }
    
    /* Copy temperature grid from params */
    for (int k = 0; k < N; k++) {
        ct->temperature[k] = ct->params.temp[k];
    }
    
    /* Read cooling rates */
    if (fread(ct->cooling_rate, sizeof(double), total_size, fp) != total_size) {
        fprintf(stderr, "Error: Failed to read cooling rates\n");
        fclose(fp);
        return -1;
    }
    
    /* Read heating rates */
    if (fread(ct->heating_rate, sizeof(double), total_size, fp) != total_size) {
        fprintf(stderr, "Error: Failed to read heating rates\n");
        fclose(fp);
        return -1;
    }
    
    fclose(fp);
    
    /* ========================================================================
     * CRITICAL: Unit Conversion
     * ========================================================================
     * CLOUDY outputs cooling/heating rates in erg/cm^3/s (volumetric).
     * The exact integration method requires erg/g/s (specific).
     * 
     * Conversion: Lambda_specific = Lambda_volumetric / rho
     * where rho = nH * m_H / X_H
     * 
     * We do this conversion here for each (density, metallicity, temperature)
     * point in the table.
     * ======================================================================== */
    printf("  Converting units: erg/cm^3/s -> erg/g/s...\n");
    
    for (int i = 0; i < L; i++) {
        double nH = ct->density[i];
        
        for (int j = 0; j < M; j++) {
            double Z_metal = ct->metallicity[j];
            
            /* Calculate gas mass density from hydrogen number density */
            double rho = nH_to_rho(nH, Z_metal);
            
            for (int k = 0; k < N; k++) {
                int idx = get_index(i, j, k, L, M, N);
                
                /* Convert from erg/cm^3/s to erg/g/s */
                ct->cooling_rate[idx] /= rho;
                ct->heating_rate[idx] /= rho;
            }
        }
    }
    
    /* Compute net cooling rate = cooling - heating */
    /* Positive net_rate means cooling (du/dt < 0), Negative means heating (du/dt > 0) */
    for (size_t idx = 0; idx < total_size; idx++) {
        ct->net_rate[idx] = ct->cooling_rate[idx] - ct->heating_rate[idx];
    }
    
    /* Build Y table for each (density, metallicity) cell */
    printf("  Building Y-function tables (Eq. 9)...\n");
    for (int i = 0; i < L; i++) {
        for (int j = 0; j < M; j++) {
            build_Y_table_for_cell(i, j);
        }
    }
    
    ct->loaded = 1;
    printf("  Cooling table loaded successfully.\n\n");
    
    return 0;
}

/* Free cooling table memory */
void free_cooling_table(void) {
    CoolingTable *ct = &g_table;
    if (ct->loaded) {
        free(ct->density);
        free(ct->metallicity);
        free(ct->temperature);
        free(ct->cooling_rate);
        free(ct->heating_rate);
        free(ct->net_rate);
        free(ct->Y_table);
        if (ct->log_T_final_table) {
            free(ct->log_T_final_table);
        }
        memset(ct, 0, sizeof(CoolingTable));
    }
}

/* ============================================================================
 * Helper function for bilinear Y interpolation (thread-safe)
 * ============================================================================ */
static inline double interp_Y_bilinear(const CoolingTable *ct, 
                                        int i, int j, int k,
                                        int L, int M, int N,
                                        double f_n, double f_z) {
    double Y00 = ct->Y_table[get_index(i,   j,   k, L, M, N)];
    double Y01 = ct->Y_table[get_index(i,   j+1, k, L, M, N)];
    double Y10 = ct->Y_table[get_index(i+1, j,   k, L, M, N)];
    double Y11 = ct->Y_table[get_index(i+1, j+1, k, L, M, N)];
    double Y0 = lerp(Y00, Y01, f_z);
    double Y1 = lerp(Y10, Y11, f_z);
    return lerp(Y0, Y1, f_n);
}

/* ============================================================================
 * Exact Time Integration (Main Algorithm)
 *
 * Based on Zhu et al. (2017), MNRAS 470, 1017 - Equations (4)-(10)
 *
 * The key idea:
 *   1. Transform the cooling equation du/dt = -Lambda(u) to dY/dt = const
 *      where Y(u) = (Lambda_ref/u_ref) * integral du/Lambda(u)  [Eq. 4]
 *   
 *   2. Advance Y by Delta_Y over timestep dt:
 *      Eq. (10): Delta_Y = (u_i/Lambda_i) * (Lambda_ref/u_ref) * (dt/t_cool)
 *      where t_cool = u/|Lambda| is the cooling time
 *      So: Delta_Y = (Lambda_ref/u_ref) * dt
 *
 *   3. Find new u (and T) by inverting Y(u_new) = Y(u_old) + Delta_Y
 *
 * ============================================================================ */
double exact_integrate(double nH, double Z, double T_init, double dt, double *T_final) {
    CoolingTable *ct = &g_table;
    
    if (!ct->loaded) {
        fprintf(stderr, "Error: Cooling table not loaded!\n");
        *T_final = T_init;
        return 0.0;
    }
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    
    /* Clamp input values to table range */
    nH = clamp(nH, ct->density[0], ct->density[L-1]);
    Z = clamp(Z, ct->metallicity[0], ct->metallicity[M-1]);
    T_init = clamp(T_init, ct->temperature[0], ct->temperature[N-1]);
    
    /* Get initial net cooling rate */
    double Lambda_init = interp_net_rate(nH, Z, T_init);
    
    /* Check if cooling/heating is negligible */
    if (fabs(Lambda_init) < EPSILON) {
        *T_final = T_init;
        return 0.0;
    }
    
    /* Determine direction: cooling (Lambda > 0) or heating (Lambda < 0) */
    int cooling = (Lambda_init > 0);
    
    /* Calculate gas mass density from nH using proper mass fractions */
    double rho = nH_to_rho(nH, Z);
    
    /* Get mean molecular weight */
    double mu_init;
#ifdef USE_GETMU
    mu_init = get_mean_molecular_weight(rho, T_init, Z);
#else
//    mu_init = calc_mean_molecular_weight(T_init, Z);
    mu_init = calculate_mu(rho,T_init, Z);
#endif
    
    /* Calculate initial internal energy (for reference, Eq. 3) */
    /* double u_init = T_to_u(T_init, mu_init); */
    (void)mu_init;  /* Used for documentation, may be used in future */
    (void)rho;      /* Used when USE_GETMU is defined */
    
    /* Find reference values at this (nH, Z) */
    int i = find_index_log(ct->density, L, nH);
    int j = find_index_log(ct->metallicity, M, Z);
    int k_ref = N / 2;
    
    double T_ref = ct->temperature[k_ref];
    double L_ref = ct->net_rate[get_index(i, j, k_ref, L, M, N)];
    if (fabs(L_ref) < EPSILON) L_ref = fabs(Lambda_init);
    
    double mu_ref;
#ifdef USE_GETMU
    mu_ref = get_mean_molecular_weight(rho, T_ref, Z);
#else
//    mu_ref = calc_mean_molecular_weight(T_ref, Z);
    mu_ref = calculate_mu(rho, T_ref, Z);
#endif
    double u_ref = T_to_u(T_ref, mu_ref);
    
    /* Eq. (10): Calculate Delta_Y for this timestep
     * 
     * The equation in the paper:
     *   Delta_Y = (u_i / Lambda_i) * (Lambda_ref / u_ref) * (dt / t_cool)
     * 
     * where t_cool = u / |Lambda|
     * 
     * Simplifying:
     *   Delta_Y = (u_i / Lambda_i) * (Lambda_ref / u_ref) * (dt * |Lambda| / u)
     *           = (Lambda_ref / u_ref) * dt * sign(Lambda)
     * 
     * For cooling (Lambda > 0): Y increases (moves to lower T)
     * For heating (Lambda < 0): Y decreases (moves to higher T)
     */
    double Delta_Y = (fabs(L_ref) / u_ref) * dt;
    
    /* Find current temperature index */
    int k_init = find_index(ct->temperature, N, T_init);
    
    /* Get interpolation weights for density and metallicity */
    double f_n = (safe_log10(nH) - safe_log10(ct->density[i])) / 
                 (safe_log10(ct->density[i+1]) - safe_log10(ct->density[i]) + 1e-30);
    double f_z = (safe_log10(Z) - safe_log10(ct->metallicity[j])) / 
                 (safe_log10(ct->metallicity[j+1]) - safe_log10(ct->metallicity[j]) + 1e-30);
    f_n = clamp(f_n, 0.0, 1.0);
    f_z = clamp(f_z, 0.0, 1.0);
    
    /* Interpolate Y at initial T (between grid points) */
    double f_t = (safe_log10(T_init) - safe_log10(ct->temperature[k_init])) / 
                 (safe_log10(ct->temperature[k_init+1]) - safe_log10(ct->temperature[k_init]) + 1e-30);
    f_t = clamp(f_t, 0.0, 1.0);
    
    double Y_init = lerp(interp_Y_bilinear(ct, i, j, k_init, L, M, N, f_n, f_z), interp_Y_bilinear(ct, i, j, k_init+1, L, M, N, f_n, f_z), f_t);
    
    /* Target Y after timestep
     * 
     * From Eq. (4): Y(u) = (#_ref/u_ref) * # du/#(u)
     * 
     * dY/dt = (#_ref/u_ref) * (du/dt)/# = (#_ref/u_ref) * (-#)/# = -#_ref/u_ref
     * 
     * So for constant dt:
     *   Delta_Y = |dY/dt| * dt = (#_ref/u_ref) * dt  (always positive)
     * 
     * But the actual change in Y is:
     *   Cooling (# > 0): T decreases # u decreases # Y decreases
     *   Heating (# < 0): T increases # u increases # Y increases
     */
    double Y_target;
    if (cooling) {
        /* Cooling: Y decreases as T decreases */
        Y_target = Y_init - Delta_Y;
    } else {
        /* Heating: Y increases as T increases */
        Y_target = Y_init + Delta_Y;
    }
    
    /* Eq. (9): Find temperature where Y(T) = Y_target by searching the table */
    /* Walk through temperature grid to find the segment containing Y_target */
    
    double T_new = T_init;
    int found = 0;
    
    if (cooling) {
        /* Cooling: Y decreases as T decreases (energy loss)
         * Search from current position toward lower temperatures
         * 
         * IMPORTANT: First check if Y_target is still within the initial segment
         * (between k_init and k_init+1) before searching downward
         */
        
        /* First, check the current segment [k_init, k_init+1] */
        if (k_init < N - 1) {
            double Y_lo = interp_Y_bilinear(ct, i, j, k_init, L, M, N, f_n, f_z);
            double Y_hi = interp_Y_bilinear(ct, i, j, k_init + 1, L, M, N, f_n, f_z);
            
            /* Y increases with T (higher k = higher T = higher Y for cooling regime) */
            if (Y_target >= Y_lo && Y_target <= Y_hi) {
                /* Target is in initial segment - interpolate */
                double frac = 0.0;
                if (fabs(Y_hi - Y_lo) > EPSILON) {
                    frac = (Y_target - Y_lo) / (Y_hi - Y_lo);
                }
                frac = clamp(frac, 0.0, 1.0);
                
                double log_T_lo = safe_log10(ct->temperature[k_init]);
                double log_T_hi = safe_log10(ct->temperature[k_init + 1]);
                T_new = pow(10.0, lerp(log_T_lo, log_T_hi, frac));
                found = 1;
            }
        }
        
        /* If not found in initial segment, search downward toward lower T */
        for (int k = k_init; k >= 0 && !found; k--) {
            /* Check for equilibrium crossing (Lambda sign change) */
            double Lambda_k = ct->net_rate[get_index(i, j, k, L, M, N)];
            if (Lambda_k <= 0) {
                /* Crossed into heating regime - find equilibrium temperature */
                if (k < k_init) {
                    double Lambda_prev = ct->net_rate[get_index(i, j, k+1, L, M, N)];
                    if (fabs(Lambda_prev - Lambda_k) > EPSILON) {
                        double frac = Lambda_prev / (Lambda_prev - Lambda_k);
                        frac = clamp(frac, 0.0, 1.0);
                        double log_T_k = safe_log10(ct->temperature[k]);
                        double log_T_prev = safe_log10(ct->temperature[k+1]);
                        T_new = pow(10.0, lerp(log_T_prev, log_T_k, frac));
                    } else {
                        T_new = ct->temperature[k+1];
                    }
                } else {
                    T_new = ct->temperature[k];
                }
                found = 1;
                break;
            }
            
            /* Check if Y_target is in segment [k-1, k] */
            if (k > 0) {
                double Y_k = interp_Y_bilinear(ct, i, j, k, L, M, N, f_n, f_z);
                double Y_km1 = interp_Y_bilinear(ct, i, j, k - 1, L, M, N, f_n, f_z);
                
                /* For cooling going down: Y[k] > Y[k-1] typically */
                double Y_lo = (Y_km1 < Y_k) ? Y_km1 : Y_k;
                double Y_hi = (Y_km1 < Y_k) ? Y_k : Y_km1;
                
                if (Y_target >= Y_lo && Y_target <= Y_hi) {
                    double frac = 0.0;
                    if (fabs(Y_k - Y_km1) > EPSILON) {
                        frac = (Y_target - Y_k) / (Y_km1 - Y_k);
                    }
                    frac = clamp(frac, 0.0, 1.0);
                    
                    double log_T_k = safe_log10(ct->temperature[k]);
                    double log_T_km1 = safe_log10(ct->temperature[k - 1]);
                    T_new = pow(10.0, lerp(log_T_k, log_T_km1, frac));
                    found = 1;
                }
            }
        }
        
        if (!found) {
            /* Reached minimum temperature */
            T_new = ct->temperature[0];
        }
    } else {
        /* Heating: search toward higher temperatures */
        for (int k = k_init; k < N - 1 && !found; k++) {
            double Y_k = interp_Y_bilinear(ct, i, j, k, L, M, N, f_n, f_z);
            double Y_k1 = interp_Y_bilinear(ct, i, j, k+1, L, M, N, f_n, f_z);
            
            /* Check if target is in this segment */
            if ((Y_target >= Y_k && Y_target <= Y_k1) || 
                (Y_target <= Y_k && Y_target >= Y_k1)) {
                /* Interpolate within segment */
                double frac = 0.0;
                if (fabs(Y_k1 - Y_k) > EPSILON) {
                    frac = (Y_target - Y_k) / (Y_k1 - Y_k);
                }
                frac = clamp(frac, 0.0, 1.0);
                
                double log_T_k = safe_log10(ct->temperature[k]);
                double log_T_k1 = safe_log10(ct->temperature[k+1]);
                T_new = pow(10.0, lerp(log_T_k, log_T_k1, frac));
                found = 1;
            }
            
            /* Check for sign change in net rate (equilibrium crossing) */
            double Lambda_k = ct->net_rate[get_index(i, j, k, L, M, N)];
            if (Lambda_k >= 0 && k < N - 1) {
                /* Crossed into cooling regime - stop at equilibrium */
                T_new = ct->temperature[k];
                found = 1;
            }
        }
        
        if (!found) {
            /* Reached maximum temperature */
            T_new = ct->temperature[N-1];
        }
    }
    
    /* Clamp final temperature to table bounds */
    T_new = clamp(T_new, ct->temperature[0], ct->temperature[N-1]);
    
    
    *T_final = T_new;
    return T_new - T_init;
}

/* ============================================================================
 * Build Lookup Table for Fast Interpolation
 *
 * This function pre-computes log10(T_final/T_init) for each grid point
 * (density[i], metallicity[j], temperature[k]) using exact_integrate().
 *
 * Storing log10(T_final/T_init) (the fractional change) provides the best
 * interpolation accuracy because:
 *   1. The ratio varies smoothly even across large temperature ranges
 *   2. Near equilibrium, the ratio is ~1 (log ~ 0), which interpolates well
 *   3. Handles both cooling (ratio < 1) and heating (ratio > 1) uniformly
 *
 * Parameters:
 *   dt - The fixed timestep [seconds] for which to build the table
 *
 * Returns:
 *   0 on success, -1 on failure
 *
 * ============================================================================ */
int build_dT_lookup_table(double dt) {
    CoolingTable *ct = &g_table;
    
    if (!ct->loaded) {
        fprintf(stderr, "Error: Cooling table must be loaded before building lookup table!\n");
        return -1;
    }
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    size_t total_size = (size_t)L * M * N;
    
    printf("Building T_ratio lookup table (log-space)...\n");
    printf("  Grid: L=%d, M=%d, N=%d (total %zu entries)\n", L, M, N, total_size);
    printf("  Timestep dt = %.6e s (%.4f Myr)\n", dt, dt / MYR_IN_SEC);
    
    /* Allocate memory for lookup table if not already allocated */
    if (ct->log_T_final_table == NULL) {
        ct->log_T_final_table = (double*)malloc(total_size * sizeof(double));
        if (!ct->log_T_final_table) {
            fprintf(stderr, "Error: Failed to allocate memory for lookup table\n");
            return -1;
        }
    }
    
    /* Store the timestep used */
    ct->dT_table_dt = dt;
    
    /* Pre-compute log10(T_final/T_init) for each grid point */
    int progress_step = L / 10;
    if (progress_step < 1) progress_step = 1;
#ifdef _OPENMP
    int id;
#pragma omp parallel for schedule(dynamic)
    for(id=0;id<L*M*N;id++){
        int i = id / (M *N);
        int j = (id/ N) % M;
        int k = id % N;
        double nH = ct->density[i];
        double Z = ct->metallicity[j];
        double T_init = ct->temperature[k];
        double T_final;
        exact_integrate(nH, Z, T_init, dt, &T_final);
        int idx = get_index(i, j, k, L, M, N);
        ct->log_T_final_table[idx] = safe_log10(T_final) - safe_log10(T_init);
    }
#else
    for (int i = 0; i < L; i++) {
        double nH = ct->density[i];
        
        if (i % progress_step == 0) {
            printf("  Progress: %d%% (density index %d/%d)\n", 
                   (int)(100.0 * i / L), i, L);
        }
        
        for (int j = 0; j < M; j++) {
            double Z = ct->metallicity[j];
            
            for (int k = 0; k < N; k++) {
                double T_init = ct->temperature[k];
                double T_final;
                
                /* Use exact_integrate to compute T_final at this grid point */
                exact_integrate(nH, Z, T_init, dt, &T_final);
                
                /* Store log10(T_final/T_init) in lookup table */
                /* This is the log of the temperature ratio */
                int idx = get_index(i, j, k, L, M, N);
                ct->log_T_final_table[idx] = safe_log10(T_final) - safe_log10(T_init);
            }
        }
    }
#endif
    
    ct->dT_table_loaded = 1;
    printf("  Lookup table built successfully.\n\n");
    
    return 0;
}

/* ============================================================================
 * Free Lookup Table
 *
 * Releases memory used by the lookup table without freeing the entire
 * cooling table.
 * ============================================================================ */
void free_dT_lookup_table(void) {
    CoolingTable *ct = &g_table;
    if (ct->log_T_final_table) {
        free(ct->log_T_final_table);
        ct->log_T_final_table = NULL;
        ct->dT_table_dt = 0.0;
        ct->dT_table_loaded = 0;
        printf("Lookup table freed.\n");
    }
}

/* ============================================================================
 * Fast Exact Integration via Lookup Table Interpolation
 *
 * This function performs the same calculation as exact_integrate() but uses
 * a pre-computed lookup table with trilinear interpolation for speed.
 *
 * The lookup table stores log10(T_final/T_init) at each grid point.
 * Interpolation is performed in log-space:
 *   1. Trilinear interpolation of log10(T_final/T_init)
 *   2. Convert: T_final = T_init * 10^(interpolated value)
 *   3. Calculate dT = T_final - T_init
 *
 * This approach provides the best accuracy because the temperature ratio
 * varies smoothly across all regimes (cooling, heating, equilibrium).
 *
 * Parameters:
 *   nH      - Hydrogen number density [cm^-3]
 *   Z       - Metallicity [Z_solar]
 *   T_init  - Initial temperature [K]
 *   T_final - Output: final temperature after cooling/heating [K]
 *
 * Returns:
 *   dT = T_final - T_init (temperature change)
 *
 * Note: If the lookup table was built with timestep dt, this function
 *       effectively integrates over that same timestep.
 *
 * ============================================================================ */
double interpolate_exact_integrate(double nH, double Z, double T_init, double *T_final) {
    CoolingTable *ct = &g_table;
    
    /* Check if tables are loaded */
    if (!ct->loaded) {
        fprintf(stderr, "Error: Cooling table not loaded!\n");
        *T_final = T_init;
        return 0.0;
    }
    
    if (!ct->dT_table_loaded || ct->log_T_final_table == NULL) {
        fprintf(stderr, "Error: Lookup table not built! Call build_dT_lookup_table(dt) first.\n");
        *T_final = T_init;
        return 0.0;
    }
    
    int L = ct->params.L;
    int M = ct->params.M;
    int N = ct->params.N;
    
    /* Clamp input values to table range */
    double nH_clamped = clamp(nH, ct->density[0], ct->density[L-1]);
    double Z_clamped = clamp(Z, ct->metallicity[0], ct->metallicity[M-1]);
    double T_clamped = clamp(T_init, ct->temperature[0], ct->temperature[N-1]);
    
    /* Find indices for density (log-spaced) */
    int i = find_index_log(ct->density, L, nH_clamped);
    double f_n;
    if (ct->density[i+1] > ct->density[i]) {
        f_n = (safe_log10(nH_clamped) - safe_log10(ct->density[i])) / 
              (safe_log10(ct->density[i+1]) - safe_log10(ct->density[i]));
    } else {
        f_n = 0.0;
    }
    f_n = clamp(f_n, 0.0, 1.0);
    
    /* Find indices for metallicity (log-spaced) */
    int j = find_index_log(ct->metallicity, M, Z_clamped);
    double f_z;
    if (ct->metallicity[j+1] > ct->metallicity[j]) {
        f_z = (safe_log10(Z_clamped) - safe_log10(ct->metallicity[j])) / 
              (safe_log10(ct->metallicity[j+1]) - safe_log10(ct->metallicity[j]));
    } else {
        f_z = 0.0;
    }
    f_z = clamp(f_z, 0.0, 1.0);
    
    /* Find indices for temperature (log-spaced interpolation) */
    int k = find_index(ct->temperature, N, T_clamped);
    double f_t;
    if (ct->temperature[k+1] > ct->temperature[k]) {
        f_t = (safe_log10(T_clamped) - safe_log10(ct->temperature[k])) / 
              (safe_log10(ct->temperature[k+1]) - safe_log10(ct->temperature[k]));
    } else {
        f_t = 0.0;
    }
    f_t = clamp(f_t, 0.0, 1.0);
    
    /* Trilinear interpolation of log10(T_final/T_init) from the lookup table */
    /* Get the 8 corner values of the interpolation cube */
    double logR000 = ct->log_T_final_table[get_index(i,   j,   k,   L, M, N)];
    double logR001 = ct->log_T_final_table[get_index(i,   j,   k+1, L, M, N)];
    double logR010 = ct->log_T_final_table[get_index(i,   j+1, k,   L, M, N)];
    double logR011 = ct->log_T_final_table[get_index(i,   j+1, k+1, L, M, N)];
    double logR100 = ct->log_T_final_table[get_index(i+1, j,   k,   L, M, N)];
    double logR101 = ct->log_T_final_table[get_index(i+1, j,   k+1, L, M, N)];
    double logR110 = ct->log_T_final_table[get_index(i+1, j+1, k,   L, M, N)];
    double logR111 = ct->log_T_final_table[get_index(i+1, j+1, k+1, L, M, N)];
    
    /* Interpolate along temperature axis */
    double logR00 = lerp(logR000, logR001, f_t);
    double logR01 = lerp(logR010, logR011, f_t);
    double logR10 = lerp(logR100, logR101, f_t);
    double logR11 = lerp(logR110, logR111, f_t);
    
    /* Interpolate along metallicity axis */
    double logR0 = lerp(logR00, logR01, f_z);
    double logR1 = lerp(logR10, logR11, f_z);
    
    /* Interpolate along density axis */
    double logR_interp = lerp(logR0, logR1, f_n);
    
    /* Convert back: T_final = T_init * 10^(log_ratio) */
    double T_new = T_init * pow(10.0, logR_interp);
    
    /* Clamp to valid temperature range */
    T_new = clamp(T_new, ct->temperature[0], ct->temperature[N-1]);
    
    *T_final = T_new;
    return T_new - T_init;
}

/* ============================================================================
 * Get the timestep used for the current dT lookup table
 *
 * Returns:
 *   The timestep [seconds] used to build the dT lookup table,
 *   or 0.0 if the table is not built.
 * ============================================================================ */
double get_dT_table_timestep(void) {
    CoolingTable *ct = &g_table;
    if (ct->dT_table_loaded) {
        return ct->dT_table_dt;
    }
    return 0.0;
}

/* ============================================================================
 * Check if dT lookup table is available
 *
 * Returns:
 *   1 if the dT lookup table is built and ready to use, 0 otherwise.
 * ============================================================================ */
int is_dT_table_loaded(void) {
    return g_table.dT_table_loaded;
}

/* ============================================================================
 * Simple Euler Integration (for comparison)
 * ============================================================================ */
double euler_integrate(double nH, double Z, double T_init, double dt, double *T_final) {
    /* Get net cooling rate */
    double Lambda = interp_net_rate(nH, Z, T_init);
    
    /* Calculate gas mass density from nH using proper mass fractions */
    double rho = nH_to_rho(nH, Z);
    (void)rho;  /* Used when USE_GETMU is defined */
    
    /* Get mean molecular weight */
    double mu;
#ifdef USE_GETMU
    mu = get_mean_molecular_weight(rho, T_init, Z);
#else
//    mu = calc_mean_molecular_weight(T_init, Z);
    mu = calc_mean_molecular_weight(T_init, Z);
    mu = calculate_mu(rho,T_init, Z);
#endif
    
    /* du/dt = -Lambda */
    double u = T_to_u(T_init, mu);
    double u_new = u - Lambda * dt;
    
    /* Prevent negative internal energy */
    if (u_new < 0) u_new = u * 0.01;
    
    *T_final = u_to_T(u_new, mu);
    return *T_final - T_init;
}

/* ============================================================================
 * Utility Functions
 * ============================================================================ */

/* Get cooling time t_cool = u / |Lambda| */
double get_cooling_time(double nH, double Z, double T) {
    double Lambda = fabs(interp_net_rate(nH, Z, T));
    if (Lambda < EPSILON) return 1.0e30;
    
    /* Calculate gas mass density from nH using proper mass fractions */
    double rho = nH_to_rho(nH, Z);
    (void)rho;  /* Used when USE_GETMU is defined */
    
    double mu;
#ifdef USE_GETMU
    mu = get_mean_molecular_weight(rho, T, Z);
#else
//    mu = calc_mean_molecular_weight(T, Z);
    mu = calculate_mu(rho,T, Z);
#endif
    
    double u = T_to_u(T, mu);
    return u / Lambda;
}

/* Get net cooling rate at (nH, Z, T) */
double get_net_cooling_rate(double nH, double Z, double T) {
    return interp_net_rate(nH, Z, T);
}

/* Print table information */
void print_table_info(void) {
    CoolingTable *ct = &g_table;
    
    if (!ct->loaded) {
        printf("Cooling table not loaded.\n");
        return;
    }
    
    printf("========================================\n");
    printf("Cooling Table Information\n");
    printf("========================================\n");
    printf("Grid dimensions:\n");
    printf("  Density:     L = %d points\n", ct->params.L);
    printf("  Metallicity: M = %d points\n", ct->params.M);
    printf("  Temperature: N = %d points\n", ct->params.N);
    printf("\nredshift %f:\n", ct->params.redshift);
    printf("\nDensity range:\n");
    printf("  [%.2e, %.2e] cm^-3\n", ct->density[0], ct->density[ct->params.L-1]);
    printf("\nMetallicity range:\n");
    printf("  [%.2e, %.2e] Z_solar\n", ct->metallicity[0], ct->metallicity[ct->params.M-1]);
    printf("\nTemperature range:\n");
    printf("  [%.2e, %.2e] K\n", ct->temperature[0], ct->temperature[ct->params.N-1]);
    printf("========================================\n\n");
}

/* ============================================================================
 * Main - Test Program
 * ============================================================================ */

#ifdef TEST_PROGRAM

int main(int argc, char *argv[]) {
    printf("================================================================\n");
    printf("  Exact Time Integration for ISM Cooling/Heating\n");
    printf("  Based on Zhu, Smith & Hernquist (2017), MNRAS 470, 1017\n");
    printf("  Implementation of Equations (4)-(10)\n");
    printf("================================================================\n\n");

    /* Initialize grid */
    if (init_mu_grid() != 0) {
        fprintf(stderr, "Failed to initialize grid.\n");
        return 1;
    }
    
    /* Load cooling table */
    const char *table_file = (argc > 1) ? argv[1] : "cooling_rate_grid.bin";
    
    if (load_cooling_table(table_file) != 0) {
        fprintf(stderr, "Failed to load cooling table from '%s'\n", table_file);
        fprintf(stderr, "Usage: %s <cooling_table.bin>\n", argv[0]);
        return 1;
    }
    
    print_table_info();
    
    /* Test parameters */
    double nH = 0.1;        /* Hydrogen number density [cm^-3] */
    double Z = 0.1;         /* Metallicity [Z_solar] */
    double T = 1.0e6;       /* Initial temperature [K] */
    double dt = 0.1 * MYR_IN_SEC;  /* Small timestep [s] */
    
    printf("=== TEST 1: Cooling Evolution (small timestep) ===\n");
    printf("Initial: nH = %.2e cm^-3, Z = %.2f Z_sun, T0 = %.2e K, dt = 0.1 Myr\n\n", nH, Z, T);
    
    printf("%10s %12s %12s %14s %14s\n", 
           "t [Myr]", "T [K]", "dT [K]", "Lambda", "t_cool [Myr]");
    printf("------------------------------------------------------------------------\n");
    
    double t = 0.0;
    for (int step = 0; step <= 100; step++) {
        double Lambda = get_net_cooling_rate(nH, Z, T);
        double t_cool = get_cooling_time(nH, Z, T) / MYR_IN_SEC;

        
        if (step == 0) {
            printf("%10.4f %12.4e %12s %14.4e %14.4f\n", 
                   t / MYR_IN_SEC, T, "---", Lambda, t_cool);
        } else {
            double T_new, dT;
            dT = exact_integrate(nH, Z, T, dt, &T_new);
            printf("%10.4f %12.4e %12.4e %14.4e %14.4f\n", 
                   t / MYR_IN_SEC, T_new, dT, Lambda, t_cool);
            T = T_new;
            
            if (T < 1.5e4 || fabs(dT) < 1.0) break;  /* Stop near equilibrium */
        }
        t += dt;
        /* Print every 10 steps after first 10 */
        if (step > 10 && step % 50 != 0) continue;
        
    }
    
    printf("\n=== TEST 2: Different Density Regimes ===\n");
    {
        double densities[] = {1e-5, 1e-3, 0.1, 10.0};
        const char *names[] = {"IGM", "CGM", "ISM", "GMC"};
        
        printf("T0 = 1e6 K, Z = 0.1 Z_sun, dt = 0.1 Myr\n\n");
        printf("%8s %12s %12s %12s %14s\n", 
               "Phase", "nH [cm^-3]", "T_init", "T_final", "t_cool [Myr]");
        printf("----------------------------------------------------------------\n");
        
        for (int i = 0; i < 4; i++) {
            double nH_test = densities[i];
            double T_test = 1e6;
            double dt_test = 0.1 * MYR_IN_SEC;
            double T_final;
            
            exact_integrate(nH_test, Z, T_test, dt_test, &T_final);
            double t_cool = get_cooling_time(nH_test, Z, T_test) / MYR_IN_SEC;
            
            printf("%8s %12.2e %12.2e %12.2e %14.4f\n", 
                   names[i], nH_test, T_test, T_final, t_cool);
        }
    }
    
    printf("\n=== TEST 3: Comparison - Exact vs Euler ===\n");
    {
        T = 1.0e6;
        nH = 0.1;
        printf("nH = 0.1 cm^-3, Z = 0.1 Z_sun, T0 = 1e6 K\n\n");
        printf("%14s %14s %14s %14s\n", "dt [Myr]", "T_exact [K]", "T_euler [K]", "Difference");
        printf("------------------------------------------------------------\n");
        
        double dts[] = {0.001, 0.01, 0.1, 1.0, 10.0};
        for (int i = 0; i < 5; i++) {
            double dt_test = dts[i] * MYR_IN_SEC;
            double T_exact, T_euler;
            exact_integrate(nH, Z, T, dt_test, &T_exact);
            euler_integrate(nH, Z, T, dt_test, &T_euler);
            printf("%14.3f %14.4e %14.4e %14.4e\n", 
                   dts[i], T_exact, T_euler, T_exact - T_euler);
        }
    }
    
    printf("\n=== TEST 4: Heating from Low Temperature ===\n");
    {
        /* Test heating at low density where UV background dominates */
        nH = 1e-5;
        T = 1000;
        dt = 0.1 * MYR_IN_SEC;
        
        printf("nH = 1e-5 cm^-3 (low density, UV heating dominant)\n");
        printf("T0 = 1000 K, Z = 0.1 Z_sun, dt = 0.1 Myr\n\n");
        
        printf("%10s %12s %12s %14s\n", "t [Myr]", "T [K]", "dT [K]", "Lambda");
        printf("----------------------------------------------------\n");
        
        t = 0.0;
        for (int step = 0; step <= 20; step++) {
            double Lambda = get_net_cooling_rate(nH, Z, T);
            
            if (step == 0) {
                printf("%10.2f %12.4e %12s %14.4e\n", t / MYR_IN_SEC, T, "---", Lambda);
            } else {
                double T_new, dT;
                dT = exact_integrate(nH, Z, T, dt, &T_new);
                printf("%10.2f %12.4e %12.4e %14.4e\n", t / MYR_IN_SEC, T_new, dT, Lambda);
                T = T_new;
            }
            t += dt;
        }
    }
    
    printf("\n=== TEST 5: Mass Fractions and Mean Molecular Weight ===\n");
    {
        printf("(Using proper mass fraction calculation: rho = nH * m_H / X)\n\n");
        printf("%10s %10s %10s %10s %10s %10s\n", 
               "Z [Z_sun]", "X_H", "Y_He", "Z_metal", "mu(1e3 K)", "mu(1e6 K)");
        printf("--------------------------------------------------------------------\n");
        
        double Z_tests[] = {0.0, 0.01, 0.1, 0.5, 1.0, 2.0, 3.0};
        for (int i = 0; i < 7; i++) {
            double Z_test = Z_tests[i];
            MassFractions mf = calc_mass_fractions(Z_test);
            double mu_cold = calc_mean_molecular_weight(1000.0, Z_test);
            double mu_hot = calc_mean_molecular_weight(1e6, Z_test);
            printf("%10.2f %10.4f %10.4f %10.6f %10.4f %10.4f\n", 
                   Z_test, mf.X, mf.Y, mf.Z, mu_cold, mu_hot);
        }
        
        printf("\nDensity conversion example (nH = 1 cm^-3):\n");
        printf("  At Z = 0.0 Z_sun: rho = %.6e g/cm^3\n", nH_to_rho(1.0, 0.0));
        printf("  At Z = 1.0 Z_sun: rho = %.6e g/cm^3\n", nH_to_rho(1.0, 1.0));
        printf("  At Z = 3.0 Z_sun: rho = %.6e g/cm^3\n", nH_to_rho(1.0, 3.0));
    }
    
    printf("\n=== TEST 6: Lookup Table and Interpolation ===\n");
    {
        /* Build the lookup table for dt = 0.1 Myr */
        double dt_lookup = 0.1 * MYR_IN_SEC;
        
        printf("Building lookup table for dt = 0.1 Myr...\n\n");
        if (build_dT_lookup_table(dt_lookup) != 0) {
            fprintf(stderr, "Failed to build lookup table\n");
        } else {
            /* First: Verify accuracy at GRID POINTS (should be very small error) */
            printf("=== Grid Point Verification (exact grid points) ===\n");
            printf("%12s %12s %12s %14s %14s %12s\n",
                   "nH [cm^-3]", "Z [Z_sun]", "T_init [K]", 
                   "T_exact [K]", "T_interp [K]", "Rel.Err(T)");
            printf("--------------------------------------------------------------------------------\n");
            
            CoolingTable *ct_test = &g_table;
            double max_grid_error = 0.0;
            int grid_tests = 0;
            
            /* Test at actual grid points */
            int test_i[] = {0, 5, 10, 15, 19};
            int test_j[] = {0, 5, 10, 15, 19};
            int test_k[] = {10, 40, 70, 100, 120};
            
            for (int ii = 0; ii < 5; ii++) {
                int i_idx = test_i[ii];
                double nH_grid = ct_test->density[i_idx];
                
                for (int jj = 0; jj < 5; jj++) {
                    int j_idx = test_j[jj];
                    double Z_grid = ct_test->metallicity[j_idx];
                    
                    for (int kk = 0; kk < 5; kk++) {
                        int k_idx = test_k[kk];
                        double T_grid = ct_test->temperature[k_idx];
                        
                        double T_exact, T_interp;
                        exact_integrate(nH_grid, Z_grid, T_grid, dt_lookup, &T_exact);
                        interpolate_exact_integrate(nH_grid, Z_grid, T_grid, &T_interp);
                        
                        double rel_error = fabs(T_interp - T_exact) / T_exact;
                        if (rel_error > max_grid_error) max_grid_error = rel_error;
                        grid_tests++;
                        
                        /* Print selected results */
                        if (jj == 2 && (ii == 0 || ii == 2 || ii == 4)) {
                            printf("%12.2e %12.2e %12.2e %14.4e %14.4e %12.2e\n",
                                   nH_grid, Z_grid, T_grid, T_exact, T_interp, rel_error);
                        }
                    }
                }
            }
            printf("--------------------------------------------------------------------------------\n");
            printf("Grid point tests: %d, Max error at grid points: %.2e\n\n", grid_tests, max_grid_error);
            
            /* Second: Test at INTERMEDIATE points (between grid points) */
            printf("=== Intermediate Point Test (between grid points) ===\n");
            printf("(Using log(T_final/T_init) ratio interpolation)\n\n");
            printf("%12s %12s %12s %14s %14s %12s\n",
                   "nH [cm^-3]", "Z [Z_sun]", "T_init [K]", 
                   "T_exact [K]", "T_interp [K]", "Rel.Err(T)");
            printf("--------------------------------------------------------------------------------\n");
            
            /* Test at various (nH, Z, T) combinations - intermediate points */
            double test_nH[] = {1e-4, 1e-2, 0.1, 1.0, 10.0};
            double test_Z[] = {0.01, 0.1, 0.5, 1.0, 2.0};
            double test_T[] = {1e4, 1e5, 1e6, 1e7};
            
            double max_rel_error = 0.0;
            int n_tests = 0;
            
            for (int i_n = 0; i_n < 5; i_n++) {
                for (int i_z = 0; i_z < 5; i_z++) {
                    for (int i_t = 0; i_t < 4; i_t++) {
                        double nH_test = test_nH[i_n];
                        double Z_test = test_Z[i_z];
                        double T_test = test_T[i_t];
                        
                        double T_exact, T_interp;
                        exact_integrate(nH_test, Z_test, T_test, dt_lookup, &T_exact);
                        interpolate_exact_integrate(nH_test, Z_test, T_test, &T_interp);
                        
                        /* Compare T_final instead of dT */
                        double rel_error = fabs(T_interp - T_exact) / T_exact;
                        
                        if (rel_error > max_rel_error) max_rel_error = rel_error;
                        n_tests++;
                        
                        /* Print selected results */
                        if (i_z == 2 && (i_n == 0 || i_n == 2 || i_n == 4)) {
                            printf("%12.2e %12.2f %12.2e %14.4e %14.4e %12.2e\n",
                                   nH_test, Z_test, T_test, T_exact, T_interp, rel_error);
                        }
                    }
                }
            }
            
            printf("--------------------------------------------------------------------------------\n");
            printf("Intermediate tests: %d, Maximum relative error in T_final: %.2e\n", n_tests, max_rel_error);
            
            /* Timing comparison */
            printf("\n=== TEST 7: Performance Comparison ===\n");
            {
                int N_iter = 10000;
                nH = 0.1;
                Z = 0.5;
                T = 1e6;
                double T_out;
                
                /* Time exact_integrate */
                clock_t start = clock();
                for (int iter = 0; iter < N_iter; iter++) {
                    exact_integrate(nH, Z, T, dt_lookup, &T_out);
                }
                clock_t end = clock();
                double time_exact = (double)(end - start) / CLOCKS_PER_SEC;
                
                /* Time interpolate_exact_integrate */
                start = clock();
                for (int iter = 0; iter < N_iter; iter++) {
                    interpolate_exact_integrate(nH, Z, T, &T_out);
                }
                end = clock();
                double time_interp = (double)(end - start) / CLOCKS_PER_SEC;
                
                printf("%d iterations at (nH=%.1e, Z=%.1f, T=%.0e):\n", N_iter, nH, Z, T);
                printf("  exact_integrate():             %.4f sec (%.2f us/call)\n", 
                       time_exact, 1e6 * time_exact / N_iter);
                printf("  interpolate_exact_integrate(): %.4f sec (%.2f us/call)\n", 
                       time_interp, 1e6 * time_interp / N_iter);
                printf("  Speedup: %.1fx\n", time_exact / (time_interp + 1e-10));
            }
            
            /* Free the dT lookup table */
            free_dT_lookup_table();
        }
    }
    
    free_cooling_table();
    
    printf("\n================================================================\n");
    printf("  Test completed successfully.\n");
    printf("================================================================\n");
    
    return 0;
}

#endif /* TEST_PROGRAM */
